server:
  port: 8081

spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/jenkins_test_db}
    username: ${POSTGRES_USER:my_user}
    password: ${POSTGRES_PASSWORD:my_password}
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        mode:
          flush: true
    show-sql: true